//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASPortal.CASWCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Welcome", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class Welcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CompanyLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageOfTheDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateFoldersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicFoldersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CompanyLogo {
            get {
                return this.CompanyLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyLogoField, value) != true)) {
                    this.CompanyLogoField = value;
                    this.RaisePropertyChanged("CompanyLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogoFileName {
            get {
                return this.LogoFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoFileNameField, value) != true)) {
                    this.LogoFileNameField = value;
                    this.RaisePropertyChanged("LogoFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageOfTheDay {
            get {
                return this.MessageOfTheDayField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageOfTheDayField, value) != true)) {
                    this.MessageOfTheDayField = value;
                    this.RaisePropertyChanged("MessageOfTheDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateFolders {
            get {
                return this.PrivateFoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateFoldersField, value) != true)) {
                    this.PrivateFoldersField = value;
                    this.RaisePropertyChanged("PrivateFolders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicFolders {
            get {
                return this.PublicFoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicFoldersField, value) != true)) {
                    this.PublicFoldersField = value;
                    this.RaisePropertyChanged("PublicFolders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folder", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class Folder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PrivateFoldersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PublicFoldersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileUploadedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileUploadedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int lvl4sequenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PrivateFolders {
            get {
                return this.PrivateFoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateFoldersField, value) != true)) {
                    this.PrivateFoldersField = value;
                    this.RaisePropertyChanged("PrivateFolders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PublicFolders {
            get {
                return this.PublicFoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicFoldersField, value) != true)) {
                    this.PublicFoldersField = value;
                    this.RaisePropertyChanged("PublicFolders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileDescription {
            get {
                return this.fileDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.fileDescriptionField, value) != true)) {
                    this.fileDescriptionField = value;
                    this.RaisePropertyChanged("fileDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileUploadedBy {
            get {
                return this.fileUploadedByField;
            }
            set {
                if ((object.ReferenceEquals(this.fileUploadedByField, value) != true)) {
                    this.fileUploadedByField = value;
                    this.RaisePropertyChanged("fileUploadedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileUploadedDate {
            get {
                return this.fileUploadedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.fileUploadedDateField, value) != true)) {
                    this.fileUploadedDateField = value;
                    this.RaisePropertyChanged("fileUploadedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lvl4sequence {
            get {
                return this.lvl4sequenceField;
            }
            set {
                if ((this.lvl4sequenceField.Equals(value) != true)) {
                    this.lvl4sequenceField = value;
                    this.RaisePropertyChanged("lvl4sequence");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DayHour", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class DayHour : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day1EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day1StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day2EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day2StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day3EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day3StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day4EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day4StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day5EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day5StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day6EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day6StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day7EndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day7StartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay1WorkingDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay2WorkingDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay3WorkingDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay4WorkingDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay5WorkingDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay6WorkingDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDay7WorkingDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day1EndHour {
            get {
                return this.Day1EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day1EndHourField, value) != true)) {
                    this.Day1EndHourField = value;
                    this.RaisePropertyChanged("Day1EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day1StartHour {
            get {
                return this.Day1StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day1StartHourField, value) != true)) {
                    this.Day1StartHourField = value;
                    this.RaisePropertyChanged("Day1StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day2EndHour {
            get {
                return this.Day2EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day2EndHourField, value) != true)) {
                    this.Day2EndHourField = value;
                    this.RaisePropertyChanged("Day2EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day2StartHour {
            get {
                return this.Day2StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day2StartHourField, value) != true)) {
                    this.Day2StartHourField = value;
                    this.RaisePropertyChanged("Day2StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day3EndHour {
            get {
                return this.Day3EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day3EndHourField, value) != true)) {
                    this.Day3EndHourField = value;
                    this.RaisePropertyChanged("Day3EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day3StartHour {
            get {
                return this.Day3StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day3StartHourField, value) != true)) {
                    this.Day3StartHourField = value;
                    this.RaisePropertyChanged("Day3StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day4EndHour {
            get {
                return this.Day4EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day4EndHourField, value) != true)) {
                    this.Day4EndHourField = value;
                    this.RaisePropertyChanged("Day4EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day4StartHour {
            get {
                return this.Day4StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day4StartHourField, value) != true)) {
                    this.Day4StartHourField = value;
                    this.RaisePropertyChanged("Day4StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day5EndHour {
            get {
                return this.Day5EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day5EndHourField, value) != true)) {
                    this.Day5EndHourField = value;
                    this.RaisePropertyChanged("Day5EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day5StartHour {
            get {
                return this.Day5StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day5StartHourField, value) != true)) {
                    this.Day5StartHourField = value;
                    this.RaisePropertyChanged("Day5StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day6EndHour {
            get {
                return this.Day6EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day6EndHourField, value) != true)) {
                    this.Day6EndHourField = value;
                    this.RaisePropertyChanged("Day6EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day6StartHour {
            get {
                return this.Day6StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day6StartHourField, value) != true)) {
                    this.Day6StartHourField = value;
                    this.RaisePropertyChanged("Day6StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day7EndHour {
            get {
                return this.Day7EndHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day7EndHourField, value) != true)) {
                    this.Day7EndHourField = value;
                    this.RaisePropertyChanged("Day7EndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day7StartHour {
            get {
                return this.Day7StartHourField;
            }
            set {
                if ((object.ReferenceEquals(this.Day7StartHourField, value) != true)) {
                    this.Day7StartHourField = value;
                    this.RaisePropertyChanged("Day7StartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay1WorkingDay {
            get {
                return this.IsDay1WorkingDayField;
            }
            set {
                if ((this.IsDay1WorkingDayField.Equals(value) != true)) {
                    this.IsDay1WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay1WorkingDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay2WorkingDay {
            get {
                return this.IsDay2WorkingDayField;
            }
            set {
                if ((this.IsDay2WorkingDayField.Equals(value) != true)) {
                    this.IsDay2WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay2WorkingDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay3WorkingDay {
            get {
                return this.IsDay3WorkingDayField;
            }
            set {
                if ((this.IsDay3WorkingDayField.Equals(value) != true)) {
                    this.IsDay3WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay3WorkingDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay4WorkingDay {
            get {
                return this.IsDay4WorkingDayField;
            }
            set {
                if ((this.IsDay4WorkingDayField.Equals(value) != true)) {
                    this.IsDay4WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay4WorkingDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay5WorkingDay {
            get {
                return this.IsDay5WorkingDayField;
            }
            set {
                if ((this.IsDay5WorkingDayField.Equals(value) != true)) {
                    this.IsDay5WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay5WorkingDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay6WorkingDay {
            get {
                return this.IsDay6WorkingDayField;
            }
            set {
                if ((this.IsDay6WorkingDayField.Equals(value) != true)) {
                    this.IsDay6WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay6WorkingDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDay7WorkingDay {
            get {
                return this.IsDay7WorkingDayField;
            }
            set {
                if ((this.IsDay7WorkingDayField.Equals(value) != true)) {
                    this.IsDay7WorkingDayField = value;
                    this.RaisePropertyChanged("IsDay7WorkingDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSlot", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class TimeSlot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublicHoliDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialInstructionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublicHoliDay {
            get {
                return this.IsPublicHoliDayField;
            }
            set {
                if ((this.IsPublicHoliDayField.Equals(value) != true)) {
                    this.IsPublicHoliDayField = value;
                    this.RaisePropertyChanged("IsPublicHoliDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialInstruction {
            get {
                return this.SpecialInstructionField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialInstructionField, value) != true)) {
                    this.SpecialInstructionField = value;
                    this.RaisePropertyChanged("SpecialInstruction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteNItem", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class SiteNItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CASPortal.CASWCFService.Item[] itemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CASPortal.CASWCFService.Site[] sitesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CASPortal.CASWCFService.Item[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CASPortal.CASWCFService.Site[] sites {
            get {
                return this.sitesField;
            }
            set {
                if ((object.ReferenceEquals(this.sitesField, value) != true)) {
                    this.sitesField = value;
                    this.RaisePropertyChanged("sites");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MaxEndHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MinStartHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MaxEndHour {
            get {
                return this.MaxEndHourField;
            }
            set {
                if ((this.MaxEndHourField.Equals(value) != true)) {
                    this.MaxEndHourField = value;
                    this.RaisePropertyChanged("MaxEndHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MinStartHour {
            get {
                return this.MinStartHourField;
            }
            set {
                if ((this.MinStartHourField.Equals(value) != true)) {
                    this.MinStartHourField = value;
                    this.RaisePropertyChanged("MinStartHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class Site : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Level4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level4 {
            get {
                return this.Level4Field;
            }
            set {
                if ((this.Level4Field.Equals(value) != true)) {
                    this.Level4Field = value;
                    this.RaisePropertyChanged("Level4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteCode {
            get {
                return this.SiteCodeField;
            }
            set {
                if ((this.SiteCodeField.Equals(value) != true)) {
                    this.SiteCodeField = value;
                    this.RaisePropertyChanged("SiteCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteNo {
            get {
                return this.SiteNoField;
            }
            set {
                if ((this.SiteNoField.Equals(value) != true)) {
                    this.SiteNoField = value;
                    this.RaisePropertyChanged("SiteNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNo {
            get {
                return this.StreetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNoField, value) != true)) {
                    this.StreetNoField = value;
                    this.RaisePropertyChanged("StreetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNode", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class TreeNode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CASPortal.CASWCFService.TreeNodeLevel1[] listLeve1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CASPortal.CASWCFService.TreeNodeLevel2[] listLeve2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CASPortal.CASWCFService.TreeNodeLevel3[] listLeve3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CASPortal.CASWCFService.TreeNodeLevel4[] listLeve4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CASPortal.CASWCFService.TreeNodeLevel1[] listLeve1 {
            get {
                return this.listLeve1Field;
            }
            set {
                if ((object.ReferenceEquals(this.listLeve1Field, value) != true)) {
                    this.listLeve1Field = value;
                    this.RaisePropertyChanged("listLeve1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CASPortal.CASWCFService.TreeNodeLevel2[] listLeve2 {
            get {
                return this.listLeve2Field;
            }
            set {
                if ((object.ReferenceEquals(this.listLeve2Field, value) != true)) {
                    this.listLeve2Field = value;
                    this.RaisePropertyChanged("listLeve2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CASPortal.CASWCFService.TreeNodeLevel3[] listLeve3 {
            get {
                return this.listLeve3Field;
            }
            set {
                if ((object.ReferenceEquals(this.listLeve3Field, value) != true)) {
                    this.listLeve3Field = value;
                    this.RaisePropertyChanged("listLeve3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CASPortal.CASWCFService.TreeNodeLevel4[] listLeve4 {
            get {
                return this.listLeve4Field;
            }
            set {
                if ((object.ReferenceEquals(this.listLeve4Field, value) != true)) {
                    this.listLeve4Field = value;
                    this.RaisePropertyChanged("listLeve4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNodeLevel1", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class TreeNodeLevel1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RootCaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectionCaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RootCaption {
            get {
                return this.RootCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RootCaptionField, value) != true)) {
                    this.RootCaptionField = value;
                    this.RaisePropertyChanged("RootCaption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionCaption {
            get {
                return this.SectionCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionCaptionField, value) != true)) {
                    this.SectionCaptionField = value;
                    this.RaisePropertyChanged("SectionCaption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID {
            get {
                return this.SectionIDField;
            }
            set {
                if ((this.SectionIDField.Equals(value) != true)) {
                    this.SectionIDField = value;
                    this.RaisePropertyChanged("SectionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNodeLevel2", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class TreeNodeLevel2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionCaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionCaption {
            get {
                return this.QuestionCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionCaptionField, value) != true)) {
                    this.QuestionCaptionField = value;
                    this.RaisePropertyChanged("QuestionCaption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID {
            get {
                return this.SectionIDField;
            }
            set {
                if ((this.SectionIDField.Equals(value) != true)) {
                    this.SectionIDField = value;
                    this.RaisePropertyChanged("SectionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNodeLevel3", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class TreeNodeLevel3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerCaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnswerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswerCaption {
            get {
                return this.AnswerCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerCaptionField, value) != true)) {
                    this.AnswerCaptionField = value;
                    this.RaisePropertyChanged("AnswerCaption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerID {
            get {
                return this.AnswerIDField;
            }
            set {
                if ((this.AnswerIDField.Equals(value) != true)) {
                    this.AnswerIDField = value;
                    this.RaisePropertyChanged("AnswerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID {
            get {
                return this.SectionIDField;
            }
            set {
                if ((this.SectionIDField.Equals(value) != true)) {
                    this.SectionIDField = value;
                    this.RaisePropertyChanged("SectionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNodeLevel4", Namespace="http://schemas.datacontract.org/2004/07/CASWCFService.Model")]
    [System.SerializableAttribute()]
    public partial class TreeNodeLevel4 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalAnswerCaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdditionalAnswerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnswerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalAnswerCaption {
            get {
                return this.AdditionalAnswerCaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalAnswerCaptionField, value) != true)) {
                    this.AdditionalAnswerCaptionField = value;
                    this.RaisePropertyChanged("AdditionalAnswerCaption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdditionalAnswerID {
            get {
                return this.AdditionalAnswerIDField;
            }
            set {
                if ((this.AdditionalAnswerIDField.Equals(value) != true)) {
                    this.AdditionalAnswerIDField = value;
                    this.RaisePropertyChanged("AdditionalAnswerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerID {
            get {
                return this.AnswerIDField;
            }
            set {
                if ((this.AnswerIDField.Equals(value) != true)) {
                    this.AnswerIDField = value;
                    this.RaisePropertyChanged("AnswerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionID {
            get {
                return this.SectionIDField;
            }
            set {
                if ((this.SectionIDField.Equals(value) != true)) {
                    this.SectionIDField = value;
                    this.RaisePropertyChanged("SectionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CASWCFService.ICASWCFService")]
    public interface ICASWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/LoginProcess", ReplyAction="http://tempuri.org/ICASWCFService/LoginProcessResponse")]
        CASPortal.CASWCFService.LoginProcessResponse LoginProcess(CASPortal.CASWCFService.LoginProcessRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/LoginProcess", ReplyAction="http://tempuri.org/ICASWCFService/LoginProcessResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.LoginProcessResponse> LoginProcessAsync(CASPortal.CASWCFService.LoginProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetCASDefaultData", ReplyAction="http://tempuri.org/ICASWCFService/GetCASDefaultDataResponse")]
        CASPortal.CASWCFService.Welcome GetCASDefaultData(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetCASDefaultData", ReplyAction="http://tempuri.org/ICASWCFService/GetCASDefaultDataResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.Welcome> GetCASDefaultDataAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/LoginMessageOfDay", ReplyAction="http://tempuri.org/ICASWCFService/LoginMessageOfDayResponse")]
        CASPortal.CASWCFService.Welcome[] LoginMessageOfDay(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/LoginMessageOfDay", ReplyAction="http://tempuri.org/ICASWCFService/LoginMessageOfDayResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.Welcome[]> LoginMessageOfDayAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPrivateFolders", ReplyAction="http://tempuri.org/ICASWCFService/GetPrivateFoldersResponse")]
        string GetPrivateFolders(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPrivateFolders", ReplyAction="http://tempuri.org/ICASWCFService/GetPrivateFoldersResponse")]
        System.Threading.Tasks.Task<string> GetPrivateFoldersAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPublicFolders", ReplyAction="http://tempuri.org/ICASWCFService/GetPublicFoldersResponse")]
        string GetPublicFolders(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPublicFolders", ReplyAction="http://tempuri.org/ICASWCFService/GetPublicFoldersResponse")]
        System.Threading.Tasks.Task<string> GetPublicFoldersAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPrivateFolderFiles", ReplyAction="http://tempuri.org/ICASWCFService/GetPrivateFolderFilesResponse")]
        CASPortal.CASWCFService.Folder[] GetPrivateFolderFiles(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string TimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPrivateFolderFiles", ReplyAction="http://tempuri.org/ICASWCFService/GetPrivateFolderFilesResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.Folder[]> GetPrivateFolderFilesAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string TimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPublicFolderFiles", ReplyAction="http://tempuri.org/ICASWCFService/GetPublicFolderFilesResponse")]
        CASPortal.CASWCFService.Folder[] GetPublicFolderFiles(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string TimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPublicFolderFiles", ReplyAction="http://tempuri.org/ICASWCFService/GetPublicFolderFilesResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.Folder[]> GetPublicFolderFilesAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string TimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPrivateFileInfo", ReplyAction="http://tempuri.org/ICASWCFService/GetPrivateFileInfoResponse")]
        byte[] GetPrivateFileInfo(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPrivateFileInfo", ReplyAction="http://tempuri.org/ICASWCFService/GetPrivateFileInfoResponse")]
        System.Threading.Tasks.Task<byte[]> GetPrivateFileInfoAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPublicFileInfo", ReplyAction="http://tempuri.org/ICASWCFService/GetPublicFileInfoResponse")]
        byte[] GetPublicFileInfo(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetPublicFileInfo", ReplyAction="http://tempuri.org/ICASWCFService/GetPublicFileInfoResponse")]
        System.Threading.Tasks.Task<byte[]> GetPublicFileInfoAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetBusinessTime", ReplyAction="http://tempuri.org/ICASWCFService/GetBusinessTimeResponse")]
        CASPortal.CASWCFService.DayHour[] GetBusinessTime(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetBusinessTime", ReplyAction="http://tempuri.org/ICASWCFService/GetBusinessTimeResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.DayHour[]> GetBusinessTimeAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetScheduledTime", ReplyAction="http://tempuri.org/ICASWCFService/GetScheduledTimeResponse")]
        CASPortal.CASWCFService.TimeSlot[] GetScheduledTime(string CompanyID, string CompanyPassword, string CustomerPassword, System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetScheduledTime", ReplyAction="http://tempuri.org/ICASWCFService/GetScheduledTimeResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.TimeSlot[]> GetScheduledTimeAsync(string CompanyID, string CompanyPassword, string CustomerPassword, System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetCategoryProductService", ReplyAction="http://tempuri.org/ICASWCFService/GetCategoryProductServiceResponse")]
        CASPortal.CASWCFService.SiteNItem GetCategoryProductService(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetCategoryProductService", ReplyAction="http://tempuri.org/ICASWCFService/GetCategoryProductServiceResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.SiteNItem> GetCategoryProductServiceAsync(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetCustomerSite", ReplyAction="http://tempuri.org/ICASWCFService/GetCustomerSiteResponse")]
        CASPortal.CASWCFService.Site[] GetCustomerSite(string CompanyID, string CompanyPassword, string CustomerPassword, string CustomerID, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetCustomerSite", ReplyAction="http://tempuri.org/ICASWCFService/GetCustomerSiteResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.Site[]> GetCustomerSiteAsync(string CompanyID, string CompanyPassword, string CustomerPassword, string CustomerID, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetTrendAnalysisTreeNodes", ReplyAction="http://tempuri.org/ICASWCFService/GetTrendAnalysisTreeNodesResponse")]
        CASPortal.CASWCFService.TreeNode GetTrendAnalysisTreeNodes(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICASWCFService/GetTrendAnalysisTreeNodes", ReplyAction="http://tempuri.org/ICASWCFService/GetTrendAnalysisTreeNodesResponse")]
        System.Threading.Tasks.Task<CASPortal.CASWCFService.TreeNode> GetTrendAnalysisTreeNodesAsync(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginProcess", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CompanyID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CompanyPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CustomerPassword;
        
        public LoginProcessRequest() {
        }
        
        public LoginProcessRequest(string CompanyID, string CompanyPassword, string CustomerID, string CustomerPassword) {
            this.CompanyID = CompanyID;
            this.CompanyPassword = CompanyPassword;
            this.CustomerID = CustomerID;
            this.CustomerPassword = CustomerPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginProcessResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginProcessResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int lvl4id;
        
        public LoginProcessResponse() {
        }
        
        public LoginProcessResponse(bool LoginProcessResult, int lvl4id) {
            this.LoginProcessResult = LoginProcessResult;
            this.lvl4id = lvl4id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICASWCFServiceChannel : CASPortal.CASWCFService.ICASWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CASWCFServiceClient : System.ServiceModel.ClientBase<CASPortal.CASWCFService.ICASWCFService>, CASPortal.CASWCFService.ICASWCFService {
        
        public CASWCFServiceClient() {
        }
        
        public CASWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CASWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CASPortal.CASWCFService.LoginProcessResponse CASPortal.CASWCFService.ICASWCFService.LoginProcess(CASPortal.CASWCFService.LoginProcessRequest request) {
            return base.Channel.LoginProcess(request);
        }
        
        public bool LoginProcess(string CompanyID, string CompanyPassword, string CustomerID, string CustomerPassword, out int lvl4id) {
            CASPortal.CASWCFService.LoginProcessRequest inValue = new CASPortal.CASWCFService.LoginProcessRequest();
            inValue.CompanyID = CompanyID;
            inValue.CompanyPassword = CompanyPassword;
            inValue.CustomerID = CustomerID;
            inValue.CustomerPassword = CustomerPassword;
            CASPortal.CASWCFService.LoginProcessResponse retVal = ((CASPortal.CASWCFService.ICASWCFService)(this)).LoginProcess(inValue);
            lvl4id = retVal.lvl4id;
            return retVal.LoginProcessResult;
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.LoginProcessResponse> LoginProcessAsync(CASPortal.CASWCFService.LoginProcessRequest request) {
            return base.Channel.LoginProcessAsync(request);
        }
        
        public CASPortal.CASWCFService.Welcome GetCASDefaultData(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID) {
            return base.Channel.GetCASDefaultData(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.Welcome> GetCASDefaultDataAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID) {
            return base.Channel.GetCASDefaultDataAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID);
        }
        
        public CASPortal.CASWCFService.Welcome[] LoginMessageOfDay(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID) {
            return base.Channel.LoginMessageOfDay(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.Welcome[]> LoginMessageOfDayAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID) {
            return base.Channel.LoginMessageOfDayAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID);
        }
        
        public string GetPrivateFolders(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID) {
            return base.Channel.GetPrivateFolders(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID);
        }
        
        public System.Threading.Tasks.Task<string> GetPrivateFoldersAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID) {
            return base.Channel.GetPrivateFoldersAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID);
        }
        
        public string GetPublicFolders(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID) {
            return base.Channel.GetPublicFolders(CompanyID, CompanyPassword, CustomerPassword, Level4ID);
        }
        
        public System.Threading.Tasks.Task<string> GetPublicFoldersAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID) {
            return base.Channel.GetPublicFoldersAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID);
        }
        
        public CASPortal.CASWCFService.Folder[] GetPrivateFolderFiles(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string TimeZoneOffset) {
            return base.Channel.GetPrivateFolderFiles(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID, FolderName, TimeZoneOffset);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.Folder[]> GetPrivateFolderFilesAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string TimeZoneOffset) {
            return base.Channel.GetPrivateFolderFilesAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID, FolderName, TimeZoneOffset);
        }
        
        public CASPortal.CASWCFService.Folder[] GetPublicFolderFiles(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string TimeZoneOffset) {
            return base.Channel.GetPublicFolderFiles(CompanyID, CompanyPassword, CustomerPassword, Level4ID, FolderName, TimeZoneOffset);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.Folder[]> GetPublicFolderFilesAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string TimeZoneOffset) {
            return base.Channel.GetPublicFolderFilesAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, FolderName, TimeZoneOffset);
        }
        
        public byte[] GetPrivateFileInfo(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string FileName) {
            return base.Channel.GetPrivateFileInfo(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID, FolderName, FileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPrivateFileInfoAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string CustomerID, string FolderName, string FileName) {
            return base.Channel.GetPrivateFileInfoAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, CustomerID, FolderName, FileName);
        }
        
        public byte[] GetPublicFileInfo(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string FileName) {
            return base.Channel.GetPublicFileInfo(CompanyID, CompanyPassword, CustomerPassword, Level4ID, FolderName, FileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPublicFileInfoAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID, string FolderName, string FileName) {
            return base.Channel.GetPublicFileInfoAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID, FolderName, FileName);
        }
        
        public CASPortal.CASWCFService.DayHour[] GetBusinessTime(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID) {
            return base.Channel.GetBusinessTime(CompanyID, CompanyPassword, CustomerPassword, Level4ID);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.DayHour[]> GetBusinessTimeAsync(string CompanyID, string CompanyPassword, string CustomerPassword, int Level4ID) {
            return base.Channel.GetBusinessTimeAsync(CompanyID, CompanyPassword, CustomerPassword, Level4ID);
        }
        
        public CASPortal.CASWCFService.TimeSlot[] GetScheduledTime(string CompanyID, string CompanyPassword, string CustomerPassword, System.DateTime startDate) {
            return base.Channel.GetScheduledTime(CompanyID, CompanyPassword, CustomerPassword, startDate);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.TimeSlot[]> GetScheduledTimeAsync(string CompanyID, string CompanyPassword, string CustomerPassword, System.DateTime startDate) {
            return base.Channel.GetScheduledTimeAsync(CompanyID, CompanyPassword, CustomerPassword, startDate);
        }
        
        public CASPortal.CASWCFService.SiteNItem GetCategoryProductService(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID) {
            return base.Channel.GetCategoryProductService(CompanyID, CompanyPassword, CustomerID, CustomerPassword, Level4ID);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.SiteNItem> GetCategoryProductServiceAsync(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID) {
            return base.Channel.GetCategoryProductServiceAsync(CompanyID, CompanyPassword, CustomerID, CustomerPassword, Level4ID);
        }
        
        public CASPortal.CASWCFService.Site[] GetCustomerSite(string CompanyID, string CompanyPassword, string CustomerPassword, string CustomerID, int Level4ID) {
            return base.Channel.GetCustomerSite(CompanyID, CompanyPassword, CustomerPassword, CustomerID, Level4ID);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.Site[]> GetCustomerSiteAsync(string CompanyID, string CompanyPassword, string CustomerPassword, string CustomerID, int Level4ID) {
            return base.Channel.GetCustomerSiteAsync(CompanyID, CompanyPassword, CustomerPassword, CustomerID, Level4ID);
        }
        
        public CASPortal.CASWCFService.TreeNode GetTrendAnalysisTreeNodes(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID) {
            return base.Channel.GetTrendAnalysisTreeNodes(CompanyID, CompanyPassword, CustomerID, CustomerPassword, Level4ID);
        }
        
        public System.Threading.Tasks.Task<CASPortal.CASWCFService.TreeNode> GetTrendAnalysisTreeNodesAsync(string CompanyID, string CompanyPassword, decimal CustomerID, string CustomerPassword, int Level4ID) {
            return base.Channel.GetTrendAnalysisTreeNodesAsync(CompanyID, CompanyPassword, CustomerID, CustomerPassword, Level4ID);
        }
    }
}
